name: CI Pipeline for HTML Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run basic HTTP test
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
