name: CI/CD Pipeline for HTML App with Docker

on:
  push:
    branches:
      - main # Trigger pipeline on push to the main branch
  pull_request:
    branches:
      - main # Trigger pipeline on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-html-app .

      - name: Run tests #(if any)
        run: |
           response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
           if [ "$response" -eq 200 ]; then
            echo "Health check passed: 200 OK"
          else
            "Health check failed: $response"
            exit 1
            fi 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy Docker image to Docker 
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-html-app ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

      - name: Deploy to server via SSH
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        # Create the SSH key file
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

        
        ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP << 'EOF'
          # Pull the latest image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

          
          docker stop my-html-app || true
          docker rm my-html-app || true

          
          docker run -d -p 8080:80 --name my-html-app ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

          echo "Deployment completed successfully!"
        EOF
