name: CI Pipeline for HTML Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install docker-compose (if not installed)
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Check that docker-compose was installed

      - name: Start local server (if applicable)
        run: |
          # Make sure your local server (e.g., Docker or other) is running before this step
          # Example for starting a local server
          docker-compose up -d

      - name: Run basic HTTP test
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Cache-control: no-cache" -H "Pragma: no-cache" -H "If-None-Match: *" -H "If-Modified-Since: 0" http://localhost:8080)
          if [ "$HTTP_STATUS" -ne 200 ] || [ "$HTTP_STATUS" -ne 304 ]; then
            echo "Unexpected HTTP status: $HTTP_STATUS"
            exit 1
          else
            echo "HTTP status is $HTTP_STATUS - OK"

  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
